### ISSUE TITLE
Widen chart

### ISSUE THREAD

**Issue by elizabet999** [reactivemarkets/react-financial-charts#178]

**Comment by markmcdowell** [comment]
Hi there, a bit more information would be helpful!

**Comment by elizabet999** [comment]
Yes, when chart gets live data it gets bigger, both candlestick and area chart. I want to make it stable and fixed when live data is applied.

**Comment by markmcdowell** [comment]
It sounds like you're setting the xExtents when updating, is that the case?

**Comment by elizabet999** [comment]
true

**Comment by markmcdowell** [comment]
Remove that setting and it should be better.

**Comment by elizabet999** [comment]
If you run also this one:
https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-intro--page
You will see that when you scroll the chart back the chart gets bigger and smaller, I want to put the chart in the middle and make my screen bigger so that I can see my chart in the same size, i dont want to see the chart is getting bigger also when it gets new live data.

**Comment by markmcdowell** [comment]
You mean you want to disable the zoom? https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-interaction--disable-zoom

**Comment by elizabet999** [comment]
True, I would like to fix Y axis scale.
