### ISSUE TITLE
chart  behaviour with real data

### ISSUE THREAD

**Issue by elizabet999** [reactivemarkets/react-financial-charts#184]
Hello,
when I apply real data and price to this chart. and when I am watching the history of the chart, and the chart gets new data, it jumps to the beginning of the chart. 
and chart is not stable. 
I want to see the history of the chart and go a bit back, but with real data, when it gets new data, it jumps to the beginning.

**Comment by markmcdowell** [comment]
The trick with this is to let the chart manage the xExtents, don't set it yourself.
I'll add an example chart to do this.
