### ISSUE TITLE
indicators and drawing tools

### ISSUE THREAD

**Issue by elizabet999** [reactivemarkets/react-financial-charts#186]
the same problem of the last chart which I saw and in this chart still remained.
https://github.com/rrag/react-stockcharts
is that when the chart gets real data, indicators and drawing tools show wrong and incorrect.
they are not stable and they can not calculate the right when there is real data, works only for stable data.

**Comment by markmcdowell** [comment]
I've yet to look into the interactive & drawing components, I do believe it's possible though because I've seen an example of the react-stockcharts using realtime and historic data as well as drawing tools.
