### ISSUE TITLE
size chart and indicators

### ISSUE THREAD

**Issue by elizabet999** [reactivemarkets/react-financial-charts#187]
when we apply indicators to the chart it can not take over the size from the chart, it needs to go below the chart when applied and when is removed the chart must go back to its size.
it is not available.

**Comment by markmcdowell** [comment]
Not sure what you want to do here, both sound possible.

Do you want to apply an indicator on top of the chart and remove it?

or

Do you want to add an indicator below the chart and then be able to remove it and the chart takes up all the space?

**Comment by elizabet999** [comment]
When i apply the indicator below the chart it does not take over size from the chart. For example chart size is 50*50 and I want to apply RSI with size of 10*50 right below the chart which must take over chart size,it means if I apply RSI, chart size must be 40*50 after that. And for example if I apply also MACD with size 10*50, the size of chart must be 30*50 after, and when I remove them, chart size must go back to 50*50

**Comment by Pa22** [comment]
@markmcdowell Did you find any solution for this issue?

**Comment by markmcdowell** [comment]
When you add a chart you set the origin and height of it, when you remove it you just reset the height to the original. See the stock chart example.

Are you doing something more complex?

**Comment by elizabet999** [comment]
Zoom-in and Zoom-out buttons get stabled when we change the size of chart. 
for example I add indicator to the chart, chart gets smaller but zoom buttons will be the same place. do you have idea how we can fix to the chart so that when indicators are added and removed, and chart gets smaller and bigger, zoom buttons also will be fixed on the chart.
Thanks.

**Comment by markmcdowell** [comment]
The zoom buttons will stay within the chart you add them to, they use the chart height to position. If this isn't happening, could you reproduce in codesandbox. Thanks.
