### ISSUE TITLE
Text Color

### ISSUE THREAD

**Issue by liaojikunwork** [reactivemarkets/react-financial-charts#375]
Hi there,

Is there any way to change the color of dates in X,Y axis? Our app uses the dark theme so we want the white color of dates.

It would be great if we can set the text color as a prop.

**Comment by markmcdowell** [comment]
Hey `tickLabelFill` is the color of the axis labels, `tickStroke` is the axis color.

**Comment by liaojikunwork** [comment]
Awesome!

Many Thanks

**Comment by oneart-dev** [comment]
@altbee Hi, may I ask you to share your code for dark theme? We need it too
