### ISSUE TITLE
Unexpected token export 

### ISSUE THREAD

**Issue by deni-rhn** [reactivemarkets/react-financial-charts#419]
- [X] bug
- [X] chore

hello everyone I implementing OHLC chart and refer on storybook/tooltip, but I got an error 
```SyntaxError: Unexpected token 'export'```
when import code 
import { Chart, ChartCanvas } from 'react-financial-charts';
my code is same as file example
Thanks,

**Comment by markmcdowell** [comment]
The library is built using es6, not sure on your build setup but you may need to use babel or modify your typescript config to transpile.

**Comment by deni-rhn** [comment]
It cause I use SSR (next js), so I should use dynamic import

**Comment by sparkle32817** [comment]
Hello @markmcdowell
I have also same issue on Next.js
I have tried to solve this with updating complier target, but failed.
I am using sample code.

![image](https://user-images.githubusercontent.com/54101792/108233328-3e494180-7176-11eb-89ac-f479b94dbd5e.png)

Hope to help this asap.

**Comment by pencilcheck** [comment]
For those who have issues, just use npx tsx when running the application and usually it will fix itself
