### ISSUE TITLE
undefined check in saveNodeType

### ISSUE THREAD

**Issue by rosyurch** [reactivemarkets/react-financial-charts#424]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
when dynamically adding a drawing this.nodes in saveNodeType function in interactive/utils.ts  is undefined, which crashes the app

#### What is the expected behavior
add a drawing
error is fixed by this check 
```export function saveNodeType(type) {
  return node => {
+    if (isDefined(this.nodes)) {
      if (isNotDefined(node) && isDefined(this.nodes[type])) {
        delete this.nodes[type]
      } else {
        this.nodes[type] = node
      }
+    } else {
+      this.nodes = []
+    }
   }
}
#### Please tell us about your environment

- Version: 0.5.1
- Browser: [all]

#### Other information

TypeError: this.nodes is undefined
saveNodeType/<

  63298 |     delete this.nodes[type];
  63299 |   } else {
  63300 |     // @ts-ignore
> 63301 |     this.nodes[type] = node;
        |     ^  63302 |   } // console.error(this.nodes)
  63303 | 
  63304 | };

**Comment by markmcdowell** [comment]
Thanks for raising the issue, we haven't got round to looking at issues in the interactive components yet. Feel free to raise a PR against the 0.5.1 tag to fix this.

**Comment by markmcdowell** [comment]
Closing as fixed in the latest alpha versions.
