### ISSUE TITLE
Error trying to add an interactive element

### ISSUE THREAD

**Issue by mattiaz9** [reactivemarkets/react-financial-charts#435]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

When I try to add an interactive element such as a Trendline I get the following error:
`TypeError: Cannot destructure property 'textWidth' of 'this.state' as it is null.` in the component `HoverTextNearMouse ` line 103.

#### Please tell us about your environment

- Version: 1.0.0-alpha.10
- Browser: all

#### Other information

The error is thrown after selecting the second point of the Trendline.
I also tried with a Fibonacci retracement and in this case the error occurs at the first click.

Looking at the code I see that the state is never being initialized as the constructor is missing.

**Comment by markmcdowell** [comment]
Yeah I need to add some examples & tests around the interactive components. Add constructor, i'll publish out a new version.

**Comment by markmcdowell** [comment]
Fixed in [v1.0.0-alpha.12](https://github.com/reactivemarkets/react-financial-charts/releases/tag/v1.0.0-alpha.12)

**Comment by mattiaz9** [comment]
Wow that was fast! Looks like it's working fine now
