### ISSUE TITLE
[BUG] Incorrect exports?

### ISSUE THREAD

**Issue by Industrial** [reactivemarkets/react-financial-charts#449]
Hi!

When I use e.g.

```
import {
  CandlestickSeries,
  Chart,
  EdgeIndicator,
  MouseCoordinateX,
  MouseCoordinateY,
  OHLCTooltip,
  XAxis,
  YAxis,
  ZoomButtons,
} from 'react-financial-charts'
```

Then I get errors for everything except Chart.

If I go to `lib/index.js` in the `node_modules` then I see

```
export { ChartCanvas } from "./ChartCanvas";
export { Chart } from "./Chart";
//# sourceMappingURL=index.js.map
```

So that makes sense :)

**Comment by markmcdowell** [comment]
The examples are using the current alpha version which is gone through quite a bit of a rewrite. v1.0.0-alpha.16 is the current latest, we're close to moving out of alpha.

**Comment by Industrial** [comment]
Hi.

I'm now using the alpha release from `@react-financial-charts/*` however the project I am trying to use it in uses Next.js. Next.js uses Webpack to create server and client side bundles and it's throwing:

```
SyntaxError: Unexpected token 'export'

external%20%22@react-financial-charts/core%22 (1:0) @ eval

> 1 | module.exports = require("@react-financial-charts/core");
```

My first reaction is 'ew eval' but yeah, I'm not sure what to do about this =)

**Comment by markmcdowell** [comment]
yes we compile to es6+, possibly related to #419. You may need to transpile the module depending on your setup.

**Comment by pencilcheck** [comment]
For those who have issues, just use `npx tsx` when running the application and usually it will fix itself
