### ISSUE TITLE
Empty chart when pan

### ISSUE THREAD

**Issue by khaphannm** [reactivemarkets/react-financial-charts#452]
I dont know if could fix the issue of scrolling chart even when no longer have data, cause the blank chart?

**Comment by markmcdowell** [comment]
Do you mean clamping the data like: https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-interaction--clamp

**Comment by khaphannm** [comment]
because clamp would stretch out the chart (I see look like zooming out) if no longer have available data. Anyway to prevent it?

**Comment by Joeao** [comment]
I have the same issue: When panning or zooming, the data disappears. I don't think this is an issue with just this library, as it occurred for me when using react-stockcharts.

I've localised the issue to [clearThreeCanvases](https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/core/src/ChartCanvas.tsx#L984). The problem is that the canvas is cleared, but whatever is supposed to happen next regarding a redraw doesn't occur until panning again.

![pan](https://user-images.githubusercontent.com/2255423/109065248-5b44be00-76fc-11eb-99d0-b37e8f3b9932.gif)

## Minimal code example:
```
const margin = { left: 30, right: 60, top: 30, bottom: 30 };
const height = 400;

const xScaleProvider = discontinuousTimeScaleProvider.inputDateAccessor((d) => d.date);
const { data, xScale, xAccessor, displayXAccessor } = xScaleProvider(props.data);

const start = xAccessor(data[data.length - 1]);
const end = xAccessor(data[Math.max(0, data.length - 150)]);
const xExtents = [start, end];

return (
	<ChartCanvas
		clamp={"both"}
		height={height}
		ratio={props.ratio}
		width={props.width}
		margin={margin}
		seriesName={"Data"}
		data={data}
		xScale={xScale}
		xAccessor={xAccessor}
		displayXAccessor={displayXAccessor}
		onLoadAfter={(start, end) => console.log(start, end)}
		xExtents={xExtents}>
		<Chart yExtents={(d) => [d.high, d.low]} padding={{ top: 10, bottom: 20 }}>
			<CandlestickSeries />
		</Chart>
	</ChartCanvas>
);
```

**Comment by markmcdowell** [comment]
Yeah think this is a separate issue, does that code always reproduce it?

**Comment by Joeao** [comment]
I can't say whether this code will always reproduce the issue so I'll make a new issue with a minimal project attached which showcases the problem. Hopefully this will make it easier to localise what's occurring. It must be quite specific to mine and maybe OP's use case as the demos don't face the same problem.

Thanks for your hard work.

**Comment by markmcdowell** [comment]
yeah in the current code is not great and I know lots of bugs like this still exist. i'm planning on starting v2 as soon as I get time to get rid of issues like this.

**Comment by Joeao** [comment]
It's been discussed in https://github.com/react-financial/react-financial-charts/issues/529 that Preact users were experiencing this issue. I'd like to note that I was also using Preact at the time of experiencing the issue, since switching to React I've not encountered it.
