### ISSUE TITLE
Support to InteractiveYCoordinate

### ISSUE THREAD

**Issue by sauloquirino** [reactivemarkets/react-financial-charts#453]
#### I'm submitting a...

- [ ] bug
- [X] feature
- [ ] chore

#### What is the current behavior
It seems that there's no documentation on how to make InteractiveYCoordinate work and all my tests failed so I'm assuming it is not supported yet.

I currently see a "TypeError: Cannot set property 'priceCoordinate' of undefined" Error.

#### What is the expected behavior

Boxes for items like orders or dynamic supports and resistances.
Please see example below:
![image](https://user-images.githubusercontent.com/23643118/98332811-3f35d900-1fb4-11eb-9680-cde53c459178.png)

#### Please tell us about your environment
- OS: Windows 10
- React: ^17.0.1 
- react-financial-charts: "^0.5.1
- Browser: [all]

**Comment by markmcdowell** [comment]
Hey, yes it should work fine with the latest alpha versions, there's a ton of fixes. Please try with 1.0.0-alpha.16

**Comment by sauloquirino** [comment]
It worked like a charm! Big and cool changes! Thanks for keeping this repo alive!
