### ISSUE TITLE
Zoom out when I update new data

### ISSUE THREAD

**Issue by Seongkyun-Yu** [reactivemarkets/react-financial-charts#454]
- [ ] question

#### What is the current behavior
Zoom out when I update new data

#### What is the expected behavior
Fix current Zooming

- Version: 1.0.0-alpha.16
- Browser: [all ]

Hi, I want create realtime chart, so I update chart data frequently

When I update new data(ex, 200 data -> 201 data), zoom setting is initialized

I want fix zoom setting that were previously changed by the user

I already try updating example 
(https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/stories/src/features/updating/BasicLineSeries.tsx)
(https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/stories/src/data/withUpdatingData.tsx)

but this is not work my project

How can I do that?

**Comment by Seongkyun-Yu** [comment]
Self-answering problem
fix xExtents value

**Comment by otaviobps** [comment]
Hi @Seongkyun-Yu, I'm trying to achieve the same.

How do you get the `xExtents` value from the zoom applied by the user?

**Comment by Seongkyun-Yu** [comment]
@otaviobps 

just fix xExtents value.

```
const xExtents = [min, max + 5] 
```

Even if data is added in real time, don't change `min`, `max` values.
