### ISSUE TITLE
Panning is not working on mobile(v1.0).

### ISSUE THREAD

**Issue by rca32** [reactivemarkets/react-financial-charts#459]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
Panning is not working on Chrome DevTool and mobile.
It's was OK on v1.0.0-alpha.16, so I suspect d3 upgrade is cause of problem.

**Comment by markmcdowell** [comment]
Sorry about that, forgot to check mobile. Fix on the PR.

**Comment by markmcdowell** [comment]
Fixed in [v1.0.1](https://github.com/reactivemarkets/react-financial-charts/releases/tag/v1.0.1
