### ISSUE TITLE
Always-opened tooltip ?

### ISSUE THREAD

**Issue by arcln** [reactivemarkets/react-financial-charts#461]
#### I'm submitting a...

- [ ] bug
- [x] feature
- [ ] chore

I'd like to display "events" on the graph which would be represented as always-opened tooltips containing some text.
For example, given a scatter plot, I'd like the tooltip of each point to be always opened.
I can't seem to find anything close to this behaviour. Is it possible? If not, would it be hard to implement? I may work on this depending on your answers.

Thanks

**Comment by markmcdowell** [comment]
Yeah you can do it with the [Annotate](https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/annotations/src/Annotate.tsx) Component and either [Label Annotation](https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/annotations/src/LabelAnnotation.tsx) or [Svg Annotation](https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/annotations/src/SvgPathAnnotation.tsx).

Something like:

```js
const labelProps = {
  text: "Hi",
};
<Annotate with={LabelAnnotation} usingProps={labelProps} when={(d) => d.example === 1} />
```

I'll see if I can find some time to add a proper example to storybook, but this is the gist.

**Comment by arcln** [comment]
This looks like exactly what I am looking for, however I doesn't seem to work for me.

Below is an example code. The components renders a blank canvas. Am I doing something wrong? I am using `v1.0.0-alpha.16`.

```javascript
const MyChart = ({ width, height, ratio }) => {
  const prices = [{
    date: new Date(),
    example: 1,
  }];

  const xScaleProvider = discontinuousTimeScaleProviderBuilder().inputDateAccessor(data => data.date);
  const { data, xScale, xAccessor, displayXAccessor } = xScaleProvider(prices);

  return (
    <ChartCanvas
      seriesName='Prices'
      data={data}
      xScale={xScale}
      xAccessor={xAccessor}
      displayXAccessor={displayXAccessor}
      width={width}
      height={height}
      ratio={ratio}
    >
      <Chart id={1} yExtents={[0, 100]}>
        <Annotate with={LabelAnnotation} usingProps={{ text: 'Hi' }} when={(d) => d.example === 1} />
      </Chart>
    </ChartCanvas>
  );
}

export default withSize({ style: { minHeight: 600 } })(withDeviceRatio()(MyChart));
```

**Comment by markmcdowell** [comment]
Added a working example, I missed 1 prop the y axis location:

```js
const prices = [{
    date: new Date(),
    example: 1,
    y: 0,
  }];
```

**Comment by arcln** [comment]
This is exactly what I needed. Thanks for your support. Closing this rn :)
