### ISSUE TITLE
don't display no-data points at all

### ISSUE THREAD

**Issue by arcln** [reactivemarkets/react-financial-charts#465]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

When I miss a part of the data, the chart acts like the data was 0, so it draws a line from the last point to 0.

#### What is the expected behavior

I'd like the line to "stop in mid-air" and not go all the way down to 0 before going back up to the next point.

#### Please tell us about your environment

- Version: 1.0.1
- Browser: all

**Comment by markmcdowell** [comment]
Take a look at the `connectNulls` property on the series, should do this.

**Comment by arcln** [comment]
This does work as expected, thanks, closing :)
