### ISSUE TITLE
prevent chart from scrolling past-end / pre-start on X axis

### ISSUE THREAD

**Issue by arcln** [reactivemarkets/react-financial-charts#466]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

When I scroll all the way left/right, the chart continues to scroll indefinitely.

#### What is the expected behavior

I would prefer the chart to stop at the first/last data point.

#### Please tell us about your environment

- Version: 1.0.1
- Browser: all

#### Other information

I tried setting `xExtents={[minX, maxX]}`, but I doesn't change anything.

**Comment by markmcdowell** [comment]
See clamping https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-interaction--clamp

**Comment by arcln** [comment]
This is what I was looking for, my bad I didn't find it in the docs. Thanks, closing :)
