### ISSUE TITLE
Graph is offset / padded by it's assigned width

### ISSUE THREAD

**Issue by Freddixx** [reactivemarkets/react-financial-charts#473]
Hi all 👋 

first of all thanks for this fork and re-write! It looks like one of the most complete financial graphing libs for react and I. definitely would like to get it up and running for my own project.

#### I'm submitting a...

- [X] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
When I create a stock chart there seems to be a padding or offset by it's own width (see screenshots).

<img src="https://user-images.githubusercontent.com/1607909/105578869-792ca500-5d83-11eb-9b30-1f7076fa237c.png" width="500" />

#### What is the expected behavior
The expected behaviour is that the chart fits into its container, like so:

<img src="https://user-images.githubusercontent.com/1607909/105578905-b7c25f80-5d83-11eb-8030-5ee48d2c1b2d.png" width="500" />

#### Please tell us about your environment
Here are my deps:

```
"dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.20",
    "@types/node": "^14.14.22",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "d3-dsv": "^2.0.0",
    "d3-time-format": "^3.0.0",
    "date-fns": "^2.16.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-financial-charts": "^1.0.1",
    "react-scripts": "4.0.1",
    "styled-components": "^5.2.1",
    "typescript": "^4.1.3",
    "web-vitals": "^0.2.4"
}
```

- Version: 1.0.1
- Browser: Chrome 87
- Blank Create React App Template

#### Other information
I tried it with both a custom graph and by copying the exact files from your first storybook example.

From what I can see it's caused  by the container which holds the canvas. If I remove its width style, everything seems to snap into place just fine (see second screenshot).

Maybe it's just something that I did wrong, looking forward to your answer!

**Comment by markmcdowell** [comment]
Hi! How are you deciding the width is it using the `withSize` HOC?

Could you post a snippet of the code you're using?

**Comment by Freddixx** [comment]
Hi @markmcdowell, this was a great hint! CRA's standard CSS is set to `text-align: center;` which then impacted the chart.

I would've never thought that the charts would inherit that behaviour. I deleted that line and now it's working just fine.

Thank you for pointing me to the right direction!
