### ISSUE TITLE
Any example where I can use JSON values as input to charts ?

### ISSUE THREAD

**Issue by rushic24** [reactivemarkets/react-financial-charts#483]
I am new to this place and finding it difficult to follow the documentation. Do you guys have a gitter/ slack/ discord group?
I'm trying to plot a chart using values fetched from an API and I don't wish to store them as a tsv file.

Thanks
~Rushi

**Comment by markmcdowell** [comment]
We're using github discussions for queries like this: https://github.com/reactivemarkets/react-financial-charts/discussions

RE: json, the library is expecting you to set the `<ChartCanvas data={yourData} ... />` where data is an array of anything. So if you're loading json and it's an array of objects you can pass it directly to the chart.
