### ISSUE TITLE
Default zoom

### ISSUE THREAD

**Issue by otaviobps** [reactivemarkets/react-financial-charts#485]
Is there anyway to set the default zoom?

Right now my chart shows all data available, but I'd like it to default zoom to only the last week. What is the correct prop to set it?

Thanks for the great work btw!

**Comment by markmcdowell** [comment]
You use the xExtents prop to define what is shown, see https://github.com/reactivemarkets/react-financial-charts/blob/10fafa021f92beb8d15843791729e557461d1469/packages/stories/src/features/StockChart.tsx#L75

**Comment by otaviobps** [comment]
Thanks for the quick reply @markmcdowell!

Right now I'm trying to use a continuous scale (all days, my data is defined from 15 to 15 minutes), so my `ChartCanvas` is defined like this:

```
<ChartCanvas
      data={state.data}
      height={height * 0.99}
      width={width * 0.99}
      ratio={1}
      margin={margin}
      seriesName="Data"
      xScale={scaleTime()}
      xAccessor={(d) => new Date(d.timestamp * 1000)}
      displayXAccessor={(d) => new Date(d.timestamp * 1000)}
      zoomMultiplier={1.05}
    >
        ...
    </ChartCanvas>
```

So the whole chart is being show:

![image](https://user-images.githubusercontent.com/28715087/109066753-4d774480-76cc-11eb-9c46-c22544a494f2.png)

If I try to add the `xExtents` prop like this:


```
<ChartCanvas
      data={state.data}
      height={height * 0.99}
      width={width * 0.99}
      ratio={1}
      margin={margin}
      seriesName="Data"
      xScale={scaleTime()}
      xAccessor={(d) => new Date(d.timestamp * 1000)}
      xExtents={[new Date(state.data.length - 50), new Date(state.data.length)]}
      displayXAccessor={(d) => new Date(d.timestamp * 1000)}
      zoomMultiplier={1.05}
    >
        ...
    </ChartCanvas>
```

Then React says that `d` is undefined in the `xAccessor`

**Comment by otaviobps** [comment]
Thanks for the quick reply @markmcdowell! It solved the issue!

**Comment by otaviobps** [comment]
I'm gonna reopen this issue because it's not working as expected.

I'm rendering a real time chart. Data is updated almost every second by a websocket. If I zoom in the chart, every time new data is rendered, the chart resizes to its default zoom (the one set at `xExtents`).

My plan is to create a state to `xExtents` and whenever the user zoom in or out, I'll update the `xExtents`.

How can I catch the zoom action?

**Comment by amaneer94** [comment]
Did you find any workaround it?
I am having same issue when tick data is reflected (managed by a state array)
