### ISSUE TITLE
click eventlistener to get coordinates?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [reactivemarkets/react-financial-charts#487]
is such feature implemented or planned?

**Comment by markmcdowell** [comment]
I'm yet to confirm it's still working but you should be able to add [ClickCallback](https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/interactive/src/ClickCallback.tsx) component.

e.g. 
```
<Chart>
  <ClickCallback onClick={...} />
</Chart>
```
