### ISSUE TITLE
Zoom out

### ISSUE THREAD

**Issue by motykadaw** [reactivemarkets/react-financial-charts#492]
#### I'm submitting a...

- [x ] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
Hey, might not be a bug, but a default behaviour that I'm too stupid to get around - there is a limitation to how far out I can scroll that seem to depend on the amount of data visible. Same thing happens in the example:
[](https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-full-screen--seconds).
How can I zoom out further? I didn't find any direct method to do so, there also seems not to be any direct feedback to how far I am so I can maybe limit the amount of data that I put into the chart.
Can You please assist?

**Comment by markmcdowell** [comment]
yeah it's not a bug it's the default behavior, this is controlled by the pointsPerPxThreshold on `ChartCavas` the default is 2 you'd have to increase that to allow further zoom out.

**Comment by motykadaw** [comment]
Thanks for the answer! I've been trying everything including `pointsPerPxThreshold` but for some reason I didn't notice any difference when changing that. It worked this time though :D 
Would be nice if the props were described in the docs or with jsdocs.
