### ISSUE TITLE
Custom horizontal line for support/resistance

### ISSUE THREAD

**Issue by madebyais** [reactivemarkets/react-financial-charts#493]
#### I'm submitting a...

- [ ] bug
- [x] feature
- [x] chore

#### Other information

Thank you for the awesome work. Is there any change to add a horizontal line? I'm planning to add a support and resistance line. Thanks!

**Comment by markmcdowell** [comment]
Sure i'm hoping to have some more time to expand out the examples but this is quite easy to do. 

For a basic horizontal line you can use the `PriceCoordinate` component:
```
<PriceCoordinate at="left" orient="left" price={60} displayFormat={format(".2f")} />
```

**Comment by madebyais** [comment]
Thank you for your awesome response @markmcdowell !
