### ISSUE TITLE
Pagination & performance issues

### ISSUE THREAD

**Issue by arcln** [reactivemarkets/react-financial-charts#494]
#### I'm submitting a...

- [ ] bug
- [x] feature
- [x] chore

#### What is the current behavior

When using big datasets, the chart is laggy / not-responding.

#### What is the expected behavior

I actually expected this to happen, however I'd like to discuss what's the best implementation for smooth charts when using big datasets.

- Is this hard to implement optimizations in the library to automatically load / unload points when they're out of visible range? This implies not rendering the whole `data` array but rather it's visible part only. Not sure if it'll fix all the lag tho.
- If the above is possible, maybe it would also be possible to implement a data fetch helper. It could be a callback prop that is invoked whenever new data is needed to continue scrolling the chart.
- If it's not possible / too hard, I suppose I can manually rotate the input data. However I don't really like this approach, because I don't know when to fetch the data. Do I need to add manual pagination buttons?

**Comment by markmcdowell** [comment]
Hi, this is always something we want to improve. v1 of the library was mostly around translating from the previous project to typescript and getting props, bugs etc... fixed.

I see v2 as changing the way it works.

how big a dataset are we talking here?

> Is this hard to implement optimizations in the library to automatically load / unload points when they're out of visible range? This implies not rendering the whole data array but rather it's visible part only. Not sure if it'll fix all the lag tho.

This is already done, only the visible part is rendered.

> If the above is possible, maybe it would also be possible to implement a data fetch helper. It could be a callback prop that is invoked whenever new data is needed to continue scrolling the chart.

This is also already done and how we use the chart, we only pull back what we want to be visible and pan or zoom loads more data.

**Comment by arcln** [comment]
Your response got me back on the right track. I got fooled by my implementation, the chart was not responsible for the lag.
I am able to display multiple series of 100k points each on the same chart with a decent performance.

I also found out about `onLoadBefore` and `onLoadAfter`, which is perfect for data fetch in my use case.

Closing this as there is no problem. Thanks for the great work!
