### ISSUE TITLE
Marker support

### ISSUE THREAD

**Issue by madebyais** [reactivemarkets/react-financial-charts#496]
- [ ] bug
- [x] feature
- [ ] chore

#### What is the current behavior
- Current annotate only supports label

#### What is the expected behavior
- Annotate should able to support any kind of html tag, so that dev can easily use icon or text

Thanks team!

**Comment by markmcdowell** [comment]
Instead of using the `LabelAnnotation` you can use the `SvgPathAnnotation` to do any shape.

**Comment by madebyais** [comment]
@markmcdowell thank you for your fast response, is there any documentation that I can follow?

**Comment by markmcdowell** [comment]
Turns out there was a bit of a bug with the svg paths but i've fixed in v1.2.1

Example here: https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-annotate--paths

Code for the example here: https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/stories/src/features/annotated/Annotated.tsx

**Comment by oneart-dev** [comment]
@markmcdowell Thank you for example. Really appreciate it. But I have a question, what if I need to show tooltip on hover of svg annotation. I found prop in GenericChartComponent "amIOnTop". I'm looking in right direction? Looks like I need create my own "Annotate" class and utilize it. Right?

**Comment by markmcdowell** [comment]
For a basic html tooltip, you can just use the tooltip prop and pass a string.

For something custom you could base an annotation on [SvgPathAnnotation](https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/annotations/src/SvgPathAnnotation.tsx) do anything you need in an svg.

**Comment by oneart-dev** [comment]
Basic html tooltip just takes ages to show up. I need to show data on hover instantly.

**Comment by oneart-dev** [comment]
I managed to do it quite nicely. Created my own class SvgPathAnnotation and simple use css and div with data to show tooltip

```
<g className={className} onClick={this.handleClick}>
        <use
          xlinkHref={`#${ID}`}
          onMouseOver={showTooltip}
          onMouseLeave={hideTooltip}
        />
        <path
          id={ID}
          transform={`translate(${x - pathWidth + 5},${y - pathHeight})`}
          d={path(datum)}
          stroke={stroke}
          fill={fill}
          opacity={opacity}
        />
      </g>
```

using `use` to extend radius of small markers for better UI experiance.

simple css
```
g.react-financial-charts-svg-path-annotation {
    pointer-events: none;
}

g.react-financial-charts-svg-path-annotation use {
    pointer-events: all;
    stroke-width: 20;
    fill: none;
    stroke-opacity: 0;
    cursor: pointer;
}

g.react-financial-charts-svg-path-annotation use:hover + * { fill: cornflowerblue; }
```
