### ISSUE TITLE
connectNulls for AreaSeries

### ISSUE THREAD

**Issue by abforce** [reactivemarkets/react-financial-charts#497]
#### I'm submitting a...

- [ ] chore
- [x] feature
- [ ] bug

#### What is the current behavior

`connectNulls` not available for `AreaSeries`. It's only available for `LineSeries`.

#### What is the expected behavior

`connectNulls` feature for `AreaSeries`.

#### Please tell us about your environment

- Version: 1.1.0

**Comment by markmcdowell** [comment]
In [v1.2.0](https://github.com/reactivemarkets/react-financial-charts/releases/tag/v1.2.0)
