### ISSUE TITLE
Reset button not working

### ISSUE THREAD

**Issue by oneart-dev** [reactivemarkets/react-financial-charts#501]
#### I'm submitting a...

- [ x ] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

Reset button in example do nothing

#### Please tell us about your environment

- Version: 1.1.0
- Browser: [ Chrome 88.0.4324.182 ]

Reset button not working on example page https://reactivemarkets.github.io/react-financial-charts/?path=/docs/features-full-screen--daily

**Comment by markmcdowell** [comment]
This is left over from the original library, you actually need to implement the reset from listening to the onReset event handler. Not ideal but that's how it currently works.
