### ISSUE TITLE
Zoom anchor not working when dragging the axis

### ISSUE THREAD

**Issue by lucafo741** [reactivemarkets/react-financial-charts#505]
#### I'm submitting a...

- [X] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
The three zoom anchor storybook examples ([to mouse](https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-interaction--zoom-anchor-to-mouse), [to last visible](https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-interaction--zoom-anchor-to-last-visible) and [to bounds](https://reactivemarkets.github.io/react-financial-charts/?path=/story/features-interaction--zoom-anchor-to-bounds)) don't work when dragging the axis.
#### What is the expected behavior
The zoom anchor to work with the zoom via axis drag
#### Please tell us about your environment

- Version: 1.1.0
- Browser: Chromium 90.0.4430.85 and Firefox 88.0

#### Other information
Tried to set the zoom anchor to be the last visible item, but had no success with the
`zoomAnchor={lastVisibleItemBasedZoomAnchor}` implementation. The zoom anchor remained centered.

**Comment by markmcdowell** [comment]
Yeah I can see the axis zoom doesn't currently use the zoomAnchor, just the mouse position.

**Comment by lucafo741** [comment]
Is there any way we can implement the "last visible" zoom anchor on the axis zoom?
