### ISSUE TITLE
XAxis with showTickLabel false left white space and conflicting with other charts

### ISSUE THREAD

**Issue by oneart-dev** [reactivemarkets/react-financial-charts#509]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

XAxis blocking mouse interaction on the top of separate indicator. 

![bug-chart-2021-04-30_12 41 29](https://user-images.githubusercontent.com/70148117/116678290-70aec080-a9a9-11eb-956f-5dbfe268e6cd.gif)

Link: https://reactivemarkets.github.io/react-financial-charts/?path=/docs/features-full-screen--daily

#### Please tell us about your environment

- Version: 1.1.0
- Browser: [ Chrome 88.0.4324.182  ]

#### Other information

Its quite easy to fix by removing XAxis component on chart above. 
Not sure if "showTickLabel={false}" should remove xAxis because now its showing empty bar.

**Comment by oneart-dev** [comment]
I post it because StockChart is a main example of library and probably should not have any issues at all.

**Comment by markmcdowell** [comment]
`showTicks={false}` is missing from the xaxis, i'll update.
