### ISSUE TITLE
Migrate to new React Context API

### ISSUE THREAD

**Issue by abbudao** [reactivemarkets/react-financial-charts#511]
#### I'm submitting a...

- [ ] bug
- [ ] feature
- [X] chore

#### What is the current behavior
We are still using the Legacy Context API.
#### What is the expected behavior
We migrate to the new Context API, as stated on the Roadmap. 

#### Other information
Has someone already picked this up? I would love to contribute but would rather avoid duplicated work. 
And if the task is available, can you provide me some pointers and expectations about it? I know this one should be pretty clear, but it doesn't hurt to ask.

**Comment by markmcdowell** [comment]
No I haven't had time to pick it up yet! I'm thinking it's fairly involved but I haven't done a full analysis.

I'd really like to move to using the provider/consumer pattern. 

https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/core/src/ChartCanvas.tsx is the top level class (huge ugly class but that's a separate issue) wrapping everything so a Provider would probably be instantiated in here.

https://github.com/reactivemarkets/react-financial-charts/blob/master/packages/core/src/GenericChartComponent.tsx is what most series inherit from.

**Comment by bobatgit** [comment]
Folks, I can only cheer the two of you on in this endeavor. I'm getting the same error as @abbudao.
