### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by MilosLoncar** [reactivemarkets/react-financial-charts#512]
#### I'm submitting a...

- [ ] bug
- [ ] feature
- [x] chore

Hey! I used react-stockcharts a while ago for a personal project. I'm at it again, saw the lib was unmaintained and came upon your fork. Great job btw, and thank you.

My goal is to import the chart and do some really basic stuff for now. Looking at storybook I'm seeing that the docs section has missing info. So I was thinking, I could figure my way on how to use it, then make a PR and we can enhance the docs a little bit.

How would you like to approach this? Should I document it in the docs tab in storybook? The previous repo had and examples folder, although since we got storybook, that's probably unnecessary.

Let me know if I'm on the right track, or if I'm missing something.

**Comment by markmcdowell** [comment]
Hi! Yes ideally everything through storybook. It does pick up some documentation from the Javadoc comments as well which is useful.

**Comment by huydhoang** [comment]
@MilosLoncar May I ask what's the current status of your work? I'm also looking for a way to import and try an example, but haven't found one yet.
