### ISSUE TITLE
Interactive Y Coordinate And Trend Line not working

### ISSUE THREAD

**Issue by romanchekashov** [reactivemarkets/react-financial-charts#513]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
Interactive Y Coordinate And Trend Line does not work. I've manage to fix it with:
- Fix Trendline And InteractiveYCoordinate:

```bash
node_modules/react-financial-charts/lib/interactive/TrendLine.js
node_modules/react-financial-charts/lib/interactive/InteractiveYCoordinate.js

constructor(props) {
    ...
    this.nodes = [];  <-- add this
}
```

```bash
node_modules/react-financial-charts/lib/interactive/wrapper/EachTrendLine.js
node_modules/react-financial-charts/lib/interactive/wrapper/EachInteractiveYCoordinate.js

constructor(props) {
    ...
    this.nodes = {};  <-- add this
}
```

#### What is the expected behavior
Should work as [http://rrag.github.io/react-stockcharts/documentation.html#/interactive_y_coordinate](http://rrag.github.io/react-stockcharts/documentation.html#/interactive_y_coordinate)
#### Please tell us about your environment

- Version: 0.5.1
- Browser: [all | Chrome XX | Firefox XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]

#### Other information
I'm still using v.0.5.1 and updating scripts in node_modules which is not good. I've looked at sources of new version and didn't find fixes so i't should be reproducible. Please check it out and add fix or write how to use Trendline And InteractiveYCoordinate? Thank you!

**Comment by markmcdowell** [comment]
Ah ok, I've yet to fully go through the interactive code. PRs are welcome.

**Comment by romanchekashov** [comment]
Well, new version changing a lot how I've used components in 0.5.1. I thought that you've just add types to existing react-stockcharts and keep same properties names in components. However you've started change the contracts before completly migrate exsisting library there at least interactive components works. So, I'm going to stick to 0.5.1 for now. Just pay attention to Interactive components because they should work. Thank you and Good luck!

**Comment by findli** [comment]
so, InteractiveYCoordinate still not in stories and not work.

**Comment by markmcdowell** [comment]
Feel free to raise a PR to add to stories.
