### ISSUE TITLE
Grid lines and xAxis labels bending

### ISSUE THREAD

**Issue by oneart-dev** [reactivemarkets/react-financial-charts#515]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

Grid lines and xAxis bending weirdly

![bug chart 2](https://user-images.githubusercontent.com/70148117/117576473-73668f80-b0e6-11eb-848d-43e227c5bc85.png)
![bug chart](https://user-images.githubusercontent.com/70148117/117576476-73ff2600-b0e6-11eb-8d76-9022ed64ee80.png)

#### Please tell us about your environment

- Version: 1.2.2
- Browser: [ Chrome ]

#### Other information

Not sure why this happening. Probably due lack of space

**Comment by oneart-dev** [comment]
This happening only on specific zoom level. Touch closure and everything fine

**Comment by markmcdowell** [comment]
Yeah it happens with d3 axis calcs, I haven't had time to work out how to avoid yet.
