### ISSUE TITLE
Documentation of the API 

### ISSUE THREAD

**Issue by Skyblueballykid** [reactivemarkets/react-financial-charts#550]
#### I'm submitting a...

- [ ] bug
- [ ] feature
- [x] chore

Hi! First of all, really nice work with this, it is one of the best financial charting libraries I have seen. 

I would like to use it in a personal project, but like other issues that have been raised, I am having some trouble understanding the API (what exports are exposed/how to import components into my project).

From what I can tell, it looks like it is necessary to first import/create a ChartCanvas component and then the specific chart and axes you want to use, like in this example from react-stockcharts? https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChart.js

Could you provide me with an example import of a CandleStickChart? I had a lot of trouble understanding the naming convention/API for charts and what the exports/default exports are, I tried a lot of combinations of imports with no success. 

I would be happy to submit a PR to update the storybook docs with an example after I get it working.

Thank you!

**Comment by dev-nll** [comment]
Please see if the answer to this question helps you: https://github.com/reactivemarkets/react-financial-charts/discussions/549

**Comment by Skyblueballykid** [comment]
That works perfectly, thank you!
