### ISSUE TITLE
Fix mouse behavior

### ISSUE THREAD

**Issue by yjiangnan** [reactivemarkets/react-financial-charts#56]
I think there are four mouse behaviors requiring improvements.

1. Activate zoom in and zoom out only when the chart is on focus, i.e., after the user clicked on it. This is helpful when the user scroll across the whole page where the chart is not the only components. The current setup will create a disturbance for the users and mess up their desired chart setup.

2. The direction of movement of the drawings when scrolling left and right should be consistent with the natural direction of the scrolling when on a touchpad (e.g., using two fingers). The current direction is opposite and creates poor user experience. I know this the correct direction when people used to use a mouse to drag the scrolling bar. However, when more and more users are more familiar to smart phones/touchpad/iPad, when they scroll left, they mean the content should go left.

3. It should not be a blank canvas when users scroll left or right or zoom in too much. That is not what most users want. When users try to move the chart to as left as possible, that normally only means they want to see the current price (in the context of other recent candle sticks as seen by default). Maybe we can still show a couple of blank spaces to indicate that there are no more candles hidden on the right, but there should be no more blank spaces than that. It is the same case when users try to move the chart content as right as possible and when users try to zoom in. Things become really annoying when the chart becomes a tight ball of mess when users do a fast zoom in (maybe accidentally), considering the difficulty to make things back to normal. The solution would be NEVER to allow the first and last candlestick to leave the left and right Y axis more than a couple of blank space, respectively.

4. When zooming out, the most recent candlestick should be fixed close to the Y axis instead of being hidden when it is originally not hidden. This is because the most recent candlestick is the most important data during trading, and most traders would like to keep it in view.

**Comment by markmcdowell** [comment]
Hey, I think 1, 3 and 4 can be done now; it's just quite hard to find the properties to do it. I'll add some examples to story book to see if that works for you.

2 - agreed scroll should be natural, I'll create a separate issue for it.

**Comment by markmcdowell** [comment]
I've added new stories on interaction, so I believe:
1. can be done with disabling zoom, enabling on click.
3. clamp the bounds.
4. anchor the zoom to either last visible or bounds depending on which you prefer.
