### ISSUE TITLE
How can I increase my charts speed

### ISSUE THREAD

**Issue by ahmadi3d** [reactivemarkets/react-financial-charts#564]
Hello
I learned that using `pointsPerPxThreshold` i can control the max zoom without doing a full plot, but my charts are extremely lag even when i zoom to 1 day, this is probably because the number of my data per pixel is pretty high, but it still shouldn't be so high that it causes lag, i have like 50k data in 10 days.
Any suggestion ?

**Comment by markmcdowell** [comment]
I haven't tested with that many points, maybe reduce the number and only pull back more when it comes into view. 50k over 10days would be about a point every 20s, I would show 1 days worth and pull back more when zoomed, panned.
