### ISSUE TITLE
MouseCoordinateY: arrowWidth broken

### ISSUE THREAD

**Issue by nameskang** [reactivemarkets/react-financial-charts#75]
#### I'm submitting a...

- [X] bug
- [ ] feature
- [ ] chore

#### What is the current behavior
arrowWidth is ignored - arrow never gets rendered.
#### What is the expected behavior
arrow should be rendered according to arrowWidth.
#### Please tell us about your environment

- Version: 0.2.3
- Browser: [all]

#### Other information
arrowWidth works properly in react-stockcharts (latest ver, 0.7.8)

**Comment by markmcdowell** [comment]
https://github.com/reactivemarkets/react-financial-charts/blob/6d060c66916d7dd9377d3ffa3808039ceb86ee15/packages/charts/src/coordinates/EdgeCoordinateV3.tsx#L248

Re-add support for arrows on edge co-ordinates.

I should be able to fix this, this afternoon.

Thanks, Mark
